### ISSUE TITLE
Compilation Instructions?

### ISSUE THREAD

**Issue by atypicalprogrammer** [iotaledger/ccurl#2]
How can we compile this on a mac?

**Comment by paulhandy** [comment]
I believe it should be:
```cmake && make```
I'll make a target rule to build a single shared object.

**Comment by paulhandy** [comment]
I've updated the Readme to include compilation instructions.

**Comment by atypicalprogrammer** [comment]
I get the following error; 

```
  The source directory

    /Users/atypical/ccurl/src

  does not contain a CMakeLists.txt file.

```

**Comment by paulhandy** [comment]
Fixed.

**Comment by atypicalprogrammer** [comment]
```
/Users/atypical/ccurl/test/test_curl.c:1:10: fatal error: 'CUnit/CUnit.h' file not found
#include "CUnit/CUnit.h"
         ^
1 error generated.
make[2]: *** [test/CMakeFiles/test_curl.dir/test_curl.c.o] Error 1
make[1]: *** [test/CMakeFiles/test_curl.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by paulhandy** [comment]
If you are running tests, you will need to install cUnit. Otherwise, feel free to comment out `add_subdirectory (test)` in the CMakeLists.txt in the parent directory.

**Comment by atypicalprogrammer** [comment]
probably i'm doing something wrong with bcunit install: 

clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lbcunit

**Comment by paulhandy** [comment]
do you have /usr/lib/libbcunit.so* and /usr/include/BCUnit/ on your computer?

**Comment by atypicalprogrammer** [comment]
No, I'm on mac, /usr/include does not even exist. Can you give more detailed instructions on how to install BCUnit? I'm probably doing it wrong :-) Sorry!!

**Comment by paulhandy** [comment]
Not a mac user, myself, and I'm without access to an osx machine, but fwiw:

http://macappstore.org/cunit/

I could add an optional macro for mac

#ifdef __APPLE__
#include "CUnit/CUnit.h"
#include "CUnit/Basic.h"
#endif

**Comment by atypicalprogrammer** [comment]
Yes, perhaps that would be best.. @domschiener can u compile on mac?

**Comment by paulhandy** [comment]
closing
