### ISSUE TITLE
license for ccurl

### ISSUE THREAD

**Issue by robertkowalski** [iotaledger/ccurl#29]
Hi!

I'm building a wallet on behalf of Bitfinex. It's going to be MIT licensed.

We have to use ccurl and the Node bindings. I didn't find any license information.

Can you state the OSS license for ccurl and the node.js bindings?

Thank you in advance!

**Comment by domschiener** [comment]
It's all MIT.

**Comment by robertkowalski** [comment]
awesome! :) I opened a PR
